openapi: 3.0.0

info:
  title: 'Finance Helper API'
  version: 1.0.0

tags:
  - name: 'Transactions'
    description: 'Transactions API'

paths:
  /api/v1/transactions:
    post:
      tags:
        - Transactions
      summary: 'Create new transaction'
      operationId: addTransaction
      requestBody:
        description: 'New transaction'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionCreationDto'
      responses:
        '201':
          description: 'Successfully created'

  /quotes/{symbol}:
    get:
      tags:
        - quotes
      summary: Get current quote for a security
      operationId: getQuote
      parameters:
        - name: symbol
          in: path
          required: true
          description: Security's symbol
          schema:
            type: string
            pattern: '[A-Z0-9]+'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteDto'
components:
  schemas:
    QuoteDto:
      description: Quote response
      type: object
      properties:
        symbol:
          type: string
          description: security's symbol
        price:
          type: number
          description: Quote value
        timestamp:
          type: string
          format: date-time

    TransactionCreationDto:
      type: object
      required:
        - categoryId
        - userId
        - transactionType
        - amount
        - transactionDateTime
      description: "Результат восстановления из архива"
      properties:
        categoryId:
          type: string
          format: uuid
          description: Telegram user id
        userId:
          type: integer
          format: int64
          description: Telegram user id
          minimum: 1
        transactionType:
          type: string
          enum: [ INCOME, EXPENSE, TRANSFER ]
        amount:
          type: number
          format: double
          minimum: 1
        transactionDateTime:
          type: string
          format: date-time