spring:
  application:
    name: financial-helper

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8910/realms/finance
          jwk-set-uri: http://localhost:8910/realms/finance/protocol/openid-connect/certs

  r2dbc:
    url: r2dbc:postgresql://localhost:5438/finance-helper
    username: postgres
    password: 0322
    pool:
      enabled: true

  data:
    r2dbc:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://localhost:27017/financial-helper
      username: root
      password: 0322

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  app:
    name: ${spring.application.name}
    version: 0.0.1

app:
  rabbitmq:
    queue: fm-common
    exchange: fm-exchange
  dev-profile: ${IS_DEV_PROFILE:false}
