spring:
  application:
    name: "financial-helper"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/{your-realm}  # ???????? ?? ??? ???????? URL
          # ???? ?? ??????????? JWK
          jwk-set-uri: http://localhost:8080/realms/{your-realm}/protocol/openid-connect/certs
          # ?????????, ??? ?? ??????????? ?????????? JWK-URI ? ??????????? ?? ???????? Keycloak

  r2dbc:
    url: r2dbc:postgresql://localhost:5438/finance-helper
    username: postgres
    password: 0322
    pool:
      enabled: true

  data:
    r2dbc:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://localhost:27017/financial-helper
      username: root
      password: 0322

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
